### ISSUE TITLE
Adding choices to add_argument() throws a runtime error (no application found)

### ISSUE THREAD

**Issue by kashyapm94** [python-restx/flask-restx#250]
I have the following project structure

```
.
├── app
│   ├── extensions.py
│   ├── __init__.py
│   └── pv_dimensioning
│       ├── controller.py
│       ├── __init__.py
│       ├── models
│       │   ├── dto.py
│       │   ├── __init__.py
│       │   └── vendor_models.py
│       ├── services
│       │   ├── calculator.py
│       │   ├── database.py
│       │   ├── data.py
│       │   ├── db_crud.py
│       │   ├── __init__.py
│       │   └── processor.py
│       └── utils
│           ├── decode_verify_jwt.py
│           ├── decorator.py
│           └── __init__.py
├── config.py
├── main.py
├── package.json
├── package-lock.json
├── Pipfile
├── Pipfile.lock
├── README.md
├── serverless.yml
└── tests
    ├── __init__.py
    ├── test_calculator.py
    ├── test_config.py
    └── test_processor.py
```

In `controller.py`, I am adding the `add_argument()` statements and parsing them in the api routes. In one of the `add_argument()` statement, I would like to add `choices` for the user. For getting the choices, I am querying from the database and getting a `list` of values available. I then convert this `list` to a `tuple`, assign it to a variable, and pass it as `choices` parameter in the `add_argument()`

**My codes:**

**data.py**

```
from ..models.vendor_models import AdminVendor

def data():
    values = AdminVendor.query.all()
    v = [value.name for value in values]
    return {'v': tuple(v)}

```

**controller.py**

```
from flask_restx import Resource, reqparse
from .services.data import data

d = data()
vendors = d['v']

parser = reqparse.RequestParser()

parser.add_argument(
    "vendor",
    choices=vendors,
    help="Select the vendor"
)

@ns.route("/")
class UserOutput(Resource):
    @ns.doc(
        "Get calculated response",
        responses={
            200: "Values returned",
            400: "Validation Error",
            403: "Not authorized"
        },
    )
    @ns.expect(parser, validation=True)
    def get(self):
        args = parser.parse_args()
        return DimensionCalculator.inputs(**args), 200
```

where `ns` is the `namespace`.

When I run the app, I get the following error:

```
Error on request:
Traceback (most recent call last):
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1020, in __call__
    return self.registry[key]
KeyError: 140392271963904

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/main.py", line 9, in <module>
    app = create_app(app_config)
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/__init__.py", line 20, in create_app
    register_blueprints(app)
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/__init__.py", line 44, in register_blueprints
    from .pv_dimensioning import dimensioning_blueprint
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/__init__.py", line 4, in <module>
    from .controller import admin_crud_ns as admin_crud_namespace
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/controller.py", line 10, in <module>
    d = data()
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/services/data.py", line 5, in data
    values = AdminVendor.query.all()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1022, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3300, in __call__
    return self.class_(**local_kw)
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 136, in __init__
    self.app = app = db.get_app()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 988, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
127.0.0.1 - - [19/Nov/2020 10:05:23] "GET /favicon.ico HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1020, in __call__
    return self.registry[key]
KeyError: 140392271963904

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/main.py", line 9, in <module>
    app = create_app(app_config)
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/__init__.py", line 20, in create_app
    register_blueprints(app)
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/__init__.py", line 44, in register_blueprints
    from .pv_dimensioning import dimensioning_blueprint
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/__init__.py", line 4, in <module>
    from .controller import admin_crud_ns as admin_crud_namespace
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/controller.py", line 10, in <module>
    d = data()
  File "/home/energycortex/Energycortex/dimensionierungs-tool-service/app/pv_dimensioning/services/data.py", line 5, in data
    values = AdminVendor.query.all()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1022, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3300, in __call__
    return self.class_(**local_kw)
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 136, in __init__
    self.app = app = db.get_app()
  File "/home/energycortex/.local/share/virtualenvs/dimensionierungs-tool-service-fJm1qbnX/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 988, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.

```

My `__init__.py` file in the `app` folder is as follows:

```
from flask import Flask

from .extensions import cors, db, ma

def create_app(app_config):
    app = Flask(__name__)

    app.config.from_object(app_config)

    register_blueprints(app)
    register_extensions(app)
    return app

def register_extensions(app):
    cors.init_app(app)
    db.init_app(app)
    ma.init_app(app)

def register_blueprints(app):
    from .pv_dimensioning import dimensioning_blueprint
    app.register_blueprint(dimensioning_blueprint)

```

and the entry point to the app is `main.py`

```
import os

from app import create_app
from app.extensions import db
from config import config_by_name

config_name = os.getenv("FLASK_CONFIG") or "default"
app_config = config_by_name[config_name]
app = create_app(app_config)

db.create_all(app=app)
```

Is there a way this error can be solved?

**Comment by j5awry** [comment]
I think the important part of this is actually related to the db, not the parser

`RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.`

Makes me think of this [specific issue with flask and FlaskSQLAlchemy](https://stackoverflow.com/questions/46540664/no-application-found-either-work-inside-a-view-function-or-push-an-application). This sort of error normally occurs when you're trying to do something that requires the Flask app context, but it isn't present.
