### ISSUE TITLE
Nested fields not working as expected

### ISSUE THREAD

**Issue by gasparuben** [python-restx/flask-restx#31]
Dear All,
I am trying to use [response marshaling](https://flask-restx.readthedocs.io/en/latest/marshalling.html) but I get an error. I managed to make the fields/marshal work as indicate in the [example - Nested fields](https://flask-restx.readthedocs.io/en/latest/marshalling.html#nested-field)

### **Code**

```python

import hashlib, hmac, time
try:
    from urllib.parse import urlencode
except ImportError:
    from urllib import urlencode
import requests
from flask_restx import Namespace, Resource, fields
from dataenhancer.secret.config import ENDPOINT_ROOMS, INDICO_SERVER, API_KEY, SECRET_KEY

namespace = Namespace('indico', description="Contrast information with Indico endpoint")

timing_fields = {}
timing_fields['date'] = fields.String(readOnly=True, description='aa')
timing_fields['tz'] = fields.String(readOnly=True, description='aa')
timing_fields['time'] = fields.String(readOnly=True, description='aa')

booking_fields = {}
booking_fields['url'] = fields.String(readOnly=True, description='aa') 
booking_fields['id'] = fields.String(readOnly=True, description='aa') 
booking_fields['creator'] = fields.String(readOnly=True, description='aa') 
booking_fields['start_dt'] = fields.Nested(timing_fields)
booking_fields['end_dt'] = fields.Nested(timing_fields)

resource_fields = {'vc_room': fields.String(readOnly=True, description='aa')}
resource_fields['event'] = fields.String(readOnly=True, description='aa')
resource_fields['booking'] = fields.Nested(booking_fields)

indico_model = namespace.model('indicoevents', resource_fields)

def _build_indico_request(path, params, api_key=None, secret_key=None, only_public=False, persistent=False):
    items = list(params.items()) if hasattr(params, 'items') else list(params)
    if api_key:
        items.append(('apikey', api_key))
    if only_public:
        items.append(('onlypublic', 'yes'))
    if secret_key:
        if not persistent:
            items.append(('timestamp', str(int(time.time()))))
        items = sorted(items, key=lambda x: x[0].lower())
        url = '%s?%s' % (path, urlencode(items))
        signature = hmac.new(secret_key.encode('utf-8'), url.encode('utf-8'),
                             hashlib.sha1).hexdigest()
        items.append(('signature', signature))
    if not items:
        return path
    return '%s?%s' % (path, urlencode(items))

@namespace.doc('class')
@namespace.route('/<string:office>')
class IndicoEventsEndpoint(Resource):
    #decorators = [require_token]

    @namespace.doc('Get_all_possible_events')
    @namespace.marshal_with(indico_model)
    def get(self, office):
        params = {
            'from': 'today',
            'to': 'today'
        }
        query = _build_indico_request('{}{}.json'.format(ENDPOINT_ROOMS, office), params, api_key=API_KEY, secret_key=SECRET_key,
                                persistent=True)   
        res = requests.get('{}/{}'.format(INDICO_SERVER, query))
        res.raise_for_status()
        return res.json()
```
I get always the following exception:

```
Unable to render schema
Traceback (most recent call last):
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/api.py", line 500, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 202, in as_dict
    **kwargs
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 391, in serialize_resource
    path[method] = self.serialize_operation(doc, method)
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 397, in serialize_operation
    'responses': self.responses_for(doc, method) or None,
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 510, in responses_for
    schema = self.serialize_schema(model)
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 563, in serialize_schema
    self.register_model(model)
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 592, in register_model
    self.register_field(field)
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 600, in register_field
    self.register_model(field.nested)
  File "/Users/r/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restx/swagger.py", line 583, in register_model
    if name not in self.api.models:
TypeError: unhashable type: 'dict'
127.0.0.1 - - [04/Feb/2020 23:07:01] "GET /api/v1/swagger.json HTTP/1.1" 500 -
127.0.0.1 - - [04/Feb/2020 23:07:01] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
```
 By doing: 

```
$ python
Python 3.6.5 (default, Apr 28 2019, 21:42:51) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_restx import fields, marshal
>>> import json
>>> timing_fields = {}
timing_fields['date'] = fields.String(readOnly=True, description='aa')
timing_fields['tz'] = fields.String(readOnly=True, description='aa')
timing_fields['time'] = fields.String(readOnly=True, description='aa')

booking_fields = {}
booking_fields['url'] = fields.String(readOnly=True, description='aa') 
booking_fields['id'] = fields.String(readOnly=True, description='aa') 
booking_fields['creator'] = fields.String(readOnly=True, description='aa') 
booking_fields['start_dt'] = fields.Nested(timing_fields)
booking_fields['end_dt'] = fields.Nested(timing_fields)

resource_fields = {'vc_room': fields.String(readOnly=True, description='aa')}
resource_fields['event'] = fields.String(readOnly=True, description='aa')
resource_fields['booking'] = fields.Nested(booking_fields)>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> 
>>> 
>>> data = {
            "vc_room": "dafdafds",
            "event": "afdasfdsfda",
            "booking": {
                "url": "https://indico-staging.xx.xx/rooms/booking/402627",
                "start_dt": {
                    "date": "2020-02-03",
                    "tz": "None",
                    "time": "13:00:00"
                },
                "end_dt": {
                    "date": "2020-02-03",
                    "tz": "None",
                    "time": "17:00:00"
                },
                "id": 402627,
                "creator": "R"
            }
}... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... 
>>> 
>>> 
>>> json.dumps(marshal(data, resource_fields))
'{"vc_room": "dafdafds", "event": "afdasfdsfda", "booking": {"url": "https://indico-staging.cern.ch/rooms/booking/402627", "id": "402627", "creator": "R", "start_dt": {"date": "2020-02-03", "tz": "None", "time": "13:00:00"}, "end_dt": {"date": "2020-02-03", "tz": "None", "time": "17:00:00"}}}'
>>> ^C
```

Is this a bug? I can provide further evidences or reduce the code to reach this issue, but it looks to me quite a general one.

Running python 3.6.5: 
Flask==1.1.1
Flask-Cors==3.0.8
flask-restplus==0.13.0
flask-restx==0.1.0

Apologies if I am missing something trivial.
Thank you.

**Comment by SVilgelm** [comment]
I think that there is an error in the documentation, because the Nested accepts a model, not just a dictionary with the fields.

So, in your case just replace:
```python
booking_fields['end_dt'] = fields.Nested(timing_fields)
resource_fields['booking'] = fields.Nested(booking_fields)
```
with
```python
booking_fields['end_dt'] = fields.Nested(namespace.model('timing_fields', timing_fields))
resource_fields['booking'] = fields.Nested(namespace.model('booking_fields', booking_fields))
```

**Comment by gasparuben** [comment]
Thank you @SVilgelm, indeed the documentation is a bit confusing about fields.Nested. As you wrote it down it does work.

I close the issue. Thank you for your help.

**Comment by SVilgelm** [comment]
Let's keep the issue opee, we need to fix the documentation.

**Comment by tjysdsg** [comment]
@SVilgelm I think allowing `fields.Nested` to accept a `dict` is very convenient. For example, if a `dict` input is detected, `fields.Nested` update its value by wrapping it with `namespace.model`.

I like feature because it allows me to generate models without knowing the namespace, therefore I don't need to pass in an extra argument.

**Comment by SVilgelm** [comment]
It can be useful, but in this case we have we have a discrepancy between the documentation and the actual behavior.

**Comment by synchronizing** [comment]
> @SVilgelm I think allowing `fields.Nested` to accept a `dict` is possibly a good feature to implement. For example, if a `dict` input is detected, `fields.Nested` update its value by wrapping it with `namespace.model`.
> 
> I like feature because it allows me to generate models without knowing the namespace, therefore I don't need to pass in an extra argument.

+1 for this behavior. As it is currently implemented, it's confusing to quickly architect a nested dictionary model.

**Comment by b33rcity** [comment]
Also getting this error, in my case while trying to use it with `fields.Wildcard`. The thing that's driving me bonkers is that _it works_ when integrated into another `Model`, but not when I try to use it on its own:

```
# serializers.py
inner = fields.Wilcard(fields.Nested({
    ...
})
outter = Model('outter', {
    'inner': fields.Nested({'*': inner})
    ...
})
inner_and_outter_model = Model('InnerNOutter', {
    '*': fields.Wildcard(fields.Nested(outter))
})

other_model = Model('OtherModel', {
    'list1': fields.List(fields.Nested(inner_and_outter_model)),
    'list2': fields.List(fields.Nested(inner_and_outter_model))
})

# api.py
namespace = Namespace(...)

@namespace.route('/<int:id>')
class Specific(Resource):
    @namespace.marshal_with(inner_and_outter_model)
    def get(self, id):
        return some_func(id)

@namespace.route('')
class Other(Resource):
    @namespace.marshal_with(other_model)
    def get(self):
        return some_other_func
```

**Comment by b33rcity** [comment]
I just realized I didn't include a stack trace yesterday--shame on me.

```
08/07/2020 08:46:57 PM - ERROR - Unable to render schema
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_restx/api.py", line 538, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 239, in as_dict
    serialized = self.serialize_resource(
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 441, in serialize_resource
    path[method] = self.serialize_operation(doc, method)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 447, in serialize_operation
    "responses": self.responses_for(doc, method) or None,
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 567, in responses_for
    schema = self.serialize_schema(model)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 632, in serialize_schema
    self.register_model(model)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 661, in register_model
    self.register_field(field)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 671, in register_field
    self.register_field(field.container)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 669, in register_field
    self.register_model(field.nested)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 652, in register_model
    if name not in self.api.models:
TypeError: unhashable type: 'dict'
```

I've been digging through this further and I've found something that I'm very tempted to call a bug.

`swagger.py:650-673`:

```
  def register_model(self, model):
        name = model.name if isinstance(model, ModelBase) else model
        if name not in self.api.models:
            raise ValueError("Model {0} not registered".format(name))
        specs = self.api.models[name]
        if name in self._registered_models:
            return ref(model)
        self._registered_models[name] = specs
        if isinstance(specs, ModelBase):
            for parent in specs.__parents__:
                self.register_model(parent)
        if isinstance(specs, Model):
            for field in itervalues(specs):
                self.register_field(field)
        return ref(model)

    def register_field(self, field):
        if isinstance(field, fields.Polymorph):
            for model in itervalues(field.mapping):
                self.register_model(model)
        elif isinstance(field, fields.Nested):
            self.register_model(field.nested)
        elif isinstance(field, (fields.List, fields.Wildcard)):
            self.register_field(field.container)
```

For a `Model` which contains a `Wildcard` which contains a `Nested`, our data bounces between these two methods twice, including one recursive call to `register_field()` when the `field` argument is a `Wildcard`. On this second call to `register_field()`, the `Wildcard` has been stripped away by passing its `container` attribute, which is a `Nested` in my case. 

At this point, we're bounced back to `register_model()`, being called against `<Nested>.nested` this time. This object is a `dict`. Since `dict` is not a `ModelBase`, `name` is set to this `dict` object on 651, which is then membership-checked on 652 against another `dict`, `self.api.models`. This, in case you're like me and had never pondered if this is a valid operation in Python, is not a valid operation in Python:

```
>>> foo = {'one': 1}
>>> boo = {'two': 2}
>>> boo in foo
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: unhashable type: 'dict'
```

A second membership check would occur a couple lines later, this time against `self._registered_models`, and one could expect the exact same error to occur.

As a serializer, the model works. I've confirmed this in `flask shell`, and as I mentioned before I am able to use it from the Swagger UI page and get correct output from it when it's wrapped in `other_model` and a `fields.List`. Swagger itself is what breaks when I attempt to pass this model to `@marshal_with()`.

I'm not sure how the workaround given in https://github.com/python-restx/flask-restx/issues/31#issuecomment-582389569 would even work, seeing as the `Namespace.model()` method seems to be acting on the same `dict`s as the `register_model()` method that's failing. Even if it worked for OP, I did try that approach in my own app and it did _not_ work for me (obligatory caveat: it's always possible I did it wrong).

In any case, it seems like it should be an easy fix: instead of 

```
elif isinstance(field, fields.Nested):
            self.register_model(field.nested)
```
perhaps 

```
elif isinstance(field, fields.Nested):
            self.register_model(field)
```
would work? This would preserve the `.name` attribute, which would be picked up correctly on 651. (I'm ready to be told it's not that simple ;) .)

**Comment by cisaacson** [comment]
The documentation is still not fixed here. 

This is the offending line (692 in `swagger.py` in `register_model`):
```
if name not in self.api.models:
```
The recommended fix above does work by wrapping the fields that are being Nested in a `model`, but the documentation for `Nested` doesn't say anything about that.

Hope that helps to get this resolved.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — looks like this is a usage question rather than a bug, so it might be a candidate for closure with a pointer.

Evidence:
- `fields.Nested(model, allow_null=True)` / `required=False` are documented behaviour for `Nested` (see `doc/marshalling.rst` "Nested field" and `flask_restx/fields.py` `Nested.__init__`). The `KeyError`-style errors usually come from the marshalled object missing the nested attribute entirely, not from a bug in `Nested`.
- The OP code mounts on a Quart-style `@api.expect` workflow without showing the full Resource definition, so it's hard to tell whether it's a marshal mismatch or a returned-payload issue.

If you (or anyone still hitting this) can share a minimal `Flask + flask-restx` snippet (no external API call) that reproduces a different shape than what the docs describe, I'm happy to dig further; otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues on this repo; the references above were verified manually against current `master`.*
