### ISSUE TITLE
Swagger not working when blueprint contains a subdomain

### ISSUE THREAD

**Issue by nilendudas1422** [python-restx/flask-restx#407]
### **Code**

```
crm_bp = Blueprint("crm", __name__, url_prefix="/api/v1/crm", subdomain="<agency_id>")
crm_api = Api(crm_bp)
crm_api.representations = {
    "application/json": output_json,
}

ns = Namespace("crm_entity", path="/entity", api=crm_api)

```

### **Repro Steps** (if applicable)
Now try to go to the documentation page :
http://test_sub_domain.hostname.com/api/v1/crm

### **Expected Behavior**
Open the documentation page.

### **Actual Behavior**
API returns 500

### **Error Messages/Stack Trace**
render_doc() got an unexpected keyword argument 'agency_id'
Traceback (most recent call last):
  File "/Users/nilendudas/.virtualenvs/sense/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nilendudas/.virtualenvs/sense/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: render_doc() got an unexpected keyword argument 'agency_id'

### **Environment**
- 3.6
- Flask version - 0.11
- Flask-RESTX version - 0.5.1
- Other installed Flask extensions

### **Additional Context**

Things are working as expected when there is no sub-domain involved.

**Comment by karanbirsense** [comment]
Any plans to fix this?
