### ISSUE TITLE
Using JSON schema in schema_model didn't work

### ISSUE THREAD

**Issue by busoff** [python-restx/flask-restx#435]
I followed the [documentation](https://flask-restx.readthedocs.io/en/latest/marshalling.html#define-model-using-json-schema)  to use JSON schema as model, but I encountered the error described as below.

### **Code**

```python
from flask import Flask
from flask_restx import Api, Resource, fields

app = Flask(__name__)
api = Api(app)

person = api.schema_model('Person', {
    'required': ['name'],
    'properties': {
        'name': {
            'type': 'string'
        },
        'age': {
            'type': 'integer'
        }
    },
    'type': 'object'
})

@api.route('/person')
class Person(Resource):
    @api.marshal_with(person)
    def get(self, **kwargs):
        return {'name': 'foo', 'age': 33}

if __name__ == '__main__':
    app.run(debug=True)
```

### **Repro Steps**
1. run the flask application
2. open a URL http://localhost:5000/person in a browser

### **Expected Behavior**
The flask application shall return a JSON response `{'name': 'foo', 'age': 33}`

### **Actual Behavior**
The flask application returns `500 `error code

### **Error Messages/Stack Trace**
(venv) ➜  webconfig git:(master) ✗ python app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 666-036-098
127.0.0.1 - - [23/Apr/2022 12:48:28] "GET /person HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/marshalling.py", line 268, in wrapper
    return marshal(
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/marshalling.py", line 58, in marshal
    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/flask_restx/marshalling.py", line 181, in _marshal
    for k, v in iteritems(fields)
  File "/mnt/work/gateway/source/webconfig/venv/lib/python3.10/site-packages/six.py", line 605, in iteritems
    return iter(d.items(**kw))
AttributeError: 'SchemaModel' object has no attribute 'items'

### **Environment**
- Python==3.10.2
- Flask==2.1.1
- flask-restx==0.5.1
- Werkzeug==2.1.1

**Comment by ErikBjare** [comment]
flask-restx does not support marshalling using JSON schemas afaik.

Here's an example where the JSON schemas are used for documentation, and normal `api.model` for marshalling: https://github.com/ActivityWatch/aw-server/blob/master/aw_server/rest.py#L74

**Comment by ErikBjare** [comment]
Actually, this is a duplicate of: https://github.com/python-restx/flask-restx/issues/142
