### ISSUE TITLE
[bug] v1.3.0 ModuleNotFoundError: No module named 'importlib.metadata' (v1.2.0 is OK)

### ISSUE THREAD

**Issue by seunggabi** [python-restx/flask-restx#586]
### ***** **BEFORE LOGGING AN ISSUE** *****

- Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- Please check if a similar issue already exists or has been closed before. Seriously, nobody here is getting paid. Help us out and take five minutes to make sure you aren't submitting a duplicate.
- Please review the [guidelines for contributing](https://github.com/python-restx/flask-restx/blob/master/CONTRIBUTING.rst)

### **Code**

```python
from your_code import your_buggy_implementation
```

### **Repro Steps** (if applicable)
1. ...
2. ...
3. Broken!

### **Expected Behavior**
A description of what you expected to happen.
```
# PYTHONPATH=$PYTHONPATH:../ python3 app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from flask_restx import Api
  File "/usr/local/lib/python3.6/site-packages/flask_restx/__init__.py", line 1, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/usr/local/lib/python3.6/site-packages/flask_restx/fields.py", line 22, in <module>
    from .marshalling import marshal
  File "/usr/local/lib/python3.6/site-packages/flask_restx/marshalling.py", line 7, in <module>
    from .utils import unpack
  File "/usr/local/lib/python3.6/site-packages/flask_restx/utils.py", line 43, in <module>
    BaseResponse = import_werkzeug_response()
  File "/usr/local/lib/python3.6/site-packages/flask_restx/utils.py", line 30, in import_werkzeug_response
    import importlib.metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```

### **Actual Behavior**
A description of the unexpected, buggy behavior.

### **Error Messages/Stack Trace**
If applicable, add the stack trace produced by the error

### **Environment**
- Python version: `3.6.8`
- Flask version: `1.1.2`
- Flask-RESTX version: `1.3.0`
- Other installed Flask extensions

### **Additional Context**
- Flask-RESTX version: `1.2.0` is OK

**Comment by peter-doggart** [comment]
The latest versions of flask-restx require python >= 3.8 (and although it may still work, only officially supports flask >= 2.0.0).

All python versions previous to 3.8 are now end of life and no longer supported.
