### ISSUE TITLE
'BlueprintSetupState' object has no attribute 'subdomain'

### ISSUE THREAD

**Issue by pansila** [python-restx/flask-restx#97]
### **Code**

```python
from quart import Blueprint, Quart
from flask_restplus import Api

blueprint = Blueprint('api', __name__)
api = Api(blueprint)
app = Quart(__name__)
app.register_blueprint(blueprint)
```

### **Repro Steps** (if applicable)
1. start the app

### **Expected Behavior**
App starts successfully

### **Actual Behavior**
An exception occurs

### **Error Messages/Stack Trace**
```
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    app.register_blueprint(blueprint)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\quart\app.py", line 1422, in register_blueprint
    blueprint.register(self, first_registration, url_prefix=url_prefix)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\quart\blueprints.py", line 755, in register
    func(state)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\flask_restx\api.py", line 840, in _deferred_blueprint_init
    self._init_app(setup_state.app)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\flask_restx\api.py", line 228, in _init_app
    self._register_specs(self.blueprint or app)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\flask_restx\api.py", line 285, in _register_specs
    resource_class_args=(self,),
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\flask_restx\api.py", line 349, in _register_view
    url, view_func=resource_func, **kwargs
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\auto-test-system-4gCsnwKR-py3.7\lib\site-packages\flask_restx\api.py", line 803, in _blueprint_setup_add_url_rule_patch
    options.setdefault("subdomain", blueprint_setup.subdomain)
AttributeError: 'BlueprintSetupState' object has no attribute 'subdomain'
```

### **Environment**
- Python 3.7
- Quart 0.11.3
- Flask-RESTX 0.2.0
- Other installed Flask extensions

### **Additional Context**

I know it's due to the different implementations between Flask and Quart, espacially add_url_rule in this case, and I understand Quart is not flask-restx's target. But by any chance to bring this excellent extenstion to Quart would be great and should be easy. Thansk a lot.

**Comment by engFelipeMonteiro** [comment]
The root of the problem is that quart.blueprint.register parameters differ from flask.blueprint.register, the others errors is workaroundable.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — looks out of scope for this repo (Quart, not Flask), and the upstream side reports it was fixed.

Evidence:
- @pgjones (Quart maintainer) replied in this very thread: *"This should be fixed in Quart 0.15 onwards."*
- `flask-restx` only targets Flask — the README and `setup.py` declare `Flask>=0.8, !=2.0.0` as the supported ASGI/WSGI framework; there's no Quart support contract.

If you're still on a Quart version older than 0.15 you'll want to upgrade there; if you're on 0.15+ and still seeing the `BlueprintSetupState.subdomain` issue against current flask-restx, please open a separate ticket with the Quart version and the full traceback. In the meantime would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues on this repo; the references above were verified manually against current `master`.*
